
package com.ycs.fe.ws.qservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryService", targetNamespace = "http://ws.ycs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectOnLoad", targetNamespace = "http://ws.ycs.com/", className = "com.ycs.fe.ws.qservice.SelectOnLoad")
    @ResponseWrapper(localName = "selectOnLoadResponse", targetNamespace = "http://ws.ycs.com/", className = "com.ycs.fe.ws.qservice.SelectOnLoadResponse")
    public String selectOnLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remoteCommandProcessor", targetNamespace = "http://ws.ycs.com/", className = "com.ycs.fe.ws.qservice.RemoteCommandProcessor")
    @ResponseWrapper(localName = "remoteCommandProcessorResponse", targetNamespace = "http://ws.ycs.com/", className = "com.ycs.fe.ws.qservice.RemoteCommandProcessorResponse")
    public String remoteCommandProcessor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
